---
title: "New QB Salary Predictions"
output: html_document
date: "2025-04-15"
---

Packages and Data Import
```{r}
# Packages, install if necessary
library(dplyr)
library(ggplot2)

# Straight from github repo, assumes all files in same directory
Salary_Data <- read.csv("./Player Salary QB.csv")
Passing_Data <- read.csv("./1999-2024 Passing Data.csv")
```

```{r}
Salary_Data <- Salary_Data %>% 
  mutate(
    Value = as.numeric(gsub("[$,]", "", Value)),
    APY = as.numeric(gsub("[$,]", "", APY)),
    Guaranteed = as.numeric(gsub("[$,]", "", Guaranteed)),
) %>% select(X, Player, Year.Signed, Years, Value, APY, Guaranteed, APY.as...Of.Cap.At.Signing) %>%
  filter(Year.Signed > 2000) %>% distinct() %>% mutate(Year.End = Year.Signed + Years)

QB_Data <- bind_rows(
  Passing_Data %>%
    inner_join(Salary_Data, by = "Player") %>%
    filter(Year < Year.Signed) %>%
    group_by(Player, Year) %>%
    slice_min(Year.Signed, with_ties = FALSE),
  
  Passing_Data %>%
    inner_join(Salary_Data, by = "Player") %>%
    filter(Year >= Year.Signed) %>%
    group_by(Player, Year) %>%
    slice_max(Year.Signed, with_ties = FALSE)
  ) %>% ungroup() %>% distinct(Player, Year, .keep_all = TRUE) %>%
  filter(Year > 2005) %>%
  filter(!is.na(QBR)) %>%
  filter(Att > 200)

# Phillip Rivers for one season in particular does not have an Success rate for some fucking reason
QB_Data[is.na(QB_Data)] <- 0

nrow(QB_Data)
```

```{r}
ggplot(Salary_Data, aes(x=Year.Signed, y=APY)) + geom_point() 
```